In [1]:
import pandas as pd
df = pd.read_csv('market_basket.csv')
df.head()


shrimp    almonds     avocado    vegetables mix green grapes  \
0         burgers  meatballs        eggs               NaN          NaN   
1         chutney        NaN         NaN               NaN          NaN   
2          turkey    avocado         NaN               NaN          NaN   
3   mineral water       milk  energy bar  whole wheat rice    green tea   
4  low fat yogurt        NaN         NaN               NaN          NaN   

  whole weat flour yams cottage cheese energy drink tomato juice  \
0              NaN  NaN            NaN          NaN          NaN   
1              NaN  NaN            NaN          NaN          NaN   
2              NaN  NaN            NaN          NaN          NaN   
3              NaN  NaN            NaN          NaN          NaN   
4              NaN  NaN            NaN          NaN          NaN   

  low fat yogurt green tea honey salad mineral water salmon antioxydant juice  \
0            NaN       NaN   NaN   NaN           NaN    NaN               NaN   
1            NaN       NaN   NaN   NaN           NaN    NaN               NaN   
2            NaN       NaN   NaN   NaN           NaN    NaN               NaN   
3            NaN       NaN   NaN   NaN           NaN    NaN               NaN   
4            NaN       NaN   NaN   NaN           NaN    NaN               NaN   

  frozen smoothie spinach  olive oil  
0             NaN     NaN        NaN  
1             NaN     NaN        NaN  
2             NaN     NaN        NaN  
3             NaN     NaN        NaN  
4             NaN     NaN        NaN

In [2]:
df.loc[[3],['vegetables mix']]

vegetables mix
3  whole wheat rice

In [3]:
df[0:3]['almonds']

0    meatballs
1          NaN
2      avocado
Name: almonds, dtype: object

In [4]:
import pandas as pd
import numpy as np

s = pd.Series(np.random.randn(100))

s

0    -0.462706
1    -0.090198
2    -0.228394
3    -0.627157
4     0.334960
        ...   
95   -0.844008
96   -0.037759
97   -1.041051
98   -0.208411
99   -0.577312
Length: 100, dtype: float64

In [5]:
s[[2,4,5]]

2   -0.228394
4    0.334960
5    0.442021
dtype: float64

In [6]:
s[2:4]

2   -0.228394
3   -0.627157
dtype: float64

In [7]:
s = pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])

In [8]:
s = pd.Series([1,2,3,4, 4, np.nan])
s.unique()

array([ 1.,  2.,  3.,  4., nan])

In [9]:
s.value_counts(normalize=True)

4.0    0.4
1.0    0.2
2.0    0.2
3.0    0.2
dtype: float64

In [10]:
a1 = np.array([1,2,3,4])
a2 = np.array([4,1,3,2])
a1 + a2

array([5, 3, 6, 6])

In [11]:
ar = np.array([[10,11, 2], [20,21, 2]])
ar.shape
type(ar)
df = pd.DataFrame(ar)
df

0   1  2
0  10  11  2
1  20  21  2

In [12]:
s1 = pd.Series([20,21])
s2 = pd.Series([10,11])
df = pd.DataFrame([s2, s1])
df

0   1
0  10  11
1  20  21

In [13]:
s1 = pd.Series(np.arange(6, 11 ,  1))
df  = pd.DataFrame({'my First column': s1})
df

my First column
0                6
1                7
2                8
3                9
4               10

In [14]:
df = pd.DataFrame([[10,11], [20,21]])
df

0   1
0  10  11
1  20  21

In [15]:
df.index = ['r1', 'r2']
df.columns = ['c1', 'c2']
df

c1  c2
r1  10  11
r2  20  21

In [16]:
df = df.reset_index()
print(df)


  index  c1  c2
0    r1  10  11
1    r2  20  21


In [17]:
df.drop('index', inplace=True, axis = 1)
df

c1  c2
0  10  11
1  20  21

In [18]:
df.drop(0, inplace =True, axis = 0)
df

c1  c2
1  20  21

In [19]:
df = pd.DataFrame([[10,11], [20,21]])
df

0   1
0  10  11
1  20  21

In [20]:
df.iloc[[0,1], 1]

0    11
1    21
Name: 1, dtype: int64

In [21]:
array = np.arange(12).reshape(3,4)
array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
array[0] - array[0]

array([0, 0, 0, 0])

In [23]:
frame = pd.DataFrame(np.arange(12).reshape(4,3), columns = list('bde'), index = ['Pes', 'Isb', 'Lhr', 'karachi'])
frame

b   d   e
Pes      0   1   2
Isb      3   4   5
Lhr      6   7   8
karachi  9  10  11

In [24]:
frame

b   d   e
Pes      0   1   2
Isb      3   4   5
Lhr      6   7   8
karachi  9  10  11

In [25]:
l = pd.Series([1,2,3,4], index=['Pes', 'Isb', 'Lhr', 'karachi'])
l
frame.sub(l, axis = 'index')

b  d  e
Pes     -1  0  1
Isb      1  2  3
Lhr      3  4  5
karachi  5  6  7

In [26]:
df = pd.read_csv('sp500.csv')
df.head()

Symbol                 Name                  Sector   Price  Dividend Yield  \
0    MMM               3M Co.             Industrials  141.14            2.12   
1    ABT  Abbott Laboratories             Health Care   39.60            1.82   
2   ABBV          AbbVie Inc.             Health Care   53.95            3.02   
3    ACN            Accenture  Information Technology   79.79            2.34   
4    ACE          ACE Limited              Financials  102.91            2.21   

   Price/Earnings  Earnings/Share  Book Value  52 week low  52 week high  \
0           20.33           6.900      26.668       107.15        143.37   
1           25.93           1.529      15.573        32.70         40.49   
2           20.87           2.570       2.954        40.10         54.78   
3           19.53           4.068       8.326        69.00         85.88   
4           10.00          10.293      86.897        84.73        104.07   

   Market Cap  EBITDA  Price/Sales  Price/Book  \
0      92.345   8.121         2.95        5.26   
1      59.477   4.359         2.74        2.55   
2      85.784   7.190         4.48       18.16   
3      50.513   4.423         1.75        9.54   
4      34.753   4.275         1.79        1.18   

                                         SEC Filings  
0  http://www.sec.gov/cgi-bin/browse-edgar?action...  
1  http://www.sec.gov/cgi-bin/browse-edgar?action...  
2  http://www.sec.gov/cgi-bin/browse-edgar?action...  
3  http://www.sec.gov/cgi-bin/browse-edgar?action...  
4  http://www.sec.gov/cgi-bin/browse-edgar?action...

In [27]:
df = pd.read_csv('sp500.csv', index_col = 'Symbol', usecols = [0,2,3,7])
df.head(3)

Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
ABT     Health Care   39.60      15.573
ABBV    Health Care   53.95       2.954

In [28]:
df.loc['ABBV','Price']

53.95

In [29]:
df.iloc[2, 1]

53.95

In [30]:
df[:3]

Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
ABT     Health Care   39.60      15.573
ABBV    Health Care   53.95       2.954

In [31]:
df.iloc[0, [1,2]]

Price         141.14
Book Value    26.668
Name: MMM, dtype: object

In [32]:
df.index.get_loc('ABBV') # returning the index

2

In [33]:
df.head()

Sector   Price  Book Value
Symbol                                            
MMM                Industrials  141.14      26.668
ABT                Health Care   39.60      15.573
ABBV               Health Care   53.95       2.954
ACN     Information Technology   79.79       8.326
ACE                 Financials  102.91      86.897

In [34]:
df[df['Price'] < 10][['Sector', 'Price']]

Sector  Price
Symbol                                    
BEAM         Consumer Discretionary   0.00
FTR     Telecommunications Services   5.81
HCBK                     Financials   9.80
HBAN                     Financials   9.10
SLM                      Financials   8.82
WIN     Telecommunications Services   9.38

In [35]:
df = pd.DataFrame([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [2, 4, 6, 8]], columns = ['A', 'B', 'C', 'D'])
df

A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12
3  2   4   6   8

In [36]:
df.iloc[[0]]

A  B  C  D
0  1  2  3  4

In [37]:
df - df.iloc[0]

A  B  C  D
0  0  0  0  0
1  4  4  4  4
2  8  8  8  8
3  1  2  3  4

In [38]:
df - df.iloc[[0]]

A    B    C    D
0  0.0  0.0  0.0  0.0
1  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN

In [39]:
df

A   B   C   D
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12
3  2   4   6   8

In [40]:
aCol = df['A']
aCol

0    1
1    5
2    9
3    2
Name: A, dtype: int64

In [41]:
df.sub(aCol, axis = 0)

A  B  C  D
0  0  1  2  3
1  0  1  2  3
2  0  1  2  3
3  0  2  4  6

In [42]:
df.sub(aCol, axis = 1)

A   B   C   D   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN

In [43]:
s= pd.Series([10, 20, 30 ,40 ,50])
s.index = ['a', 'b' ,'c', 'd', 'e']
s

a    10
b    20
c    30
d    40
e    50
dtype: int64

In [44]:
s1 = pd.Series([0,1,2], index = [0, 1, 2])
s2 = pd.Series([3, 4, 5], index = ['0', '1','2'])
# s2.index = [0,1,2]
s1

0    0
1    1
2    2
dtype: int64

In [45]:
s2

0    3
1    4
2    5
dtype: int64

In [46]:
s1 + s2

0   NaN
1   NaN
2   NaN
0   NaN
1   NaN
2   NaN
dtype: float64

In [47]:
s1 = pd.Series(['red', 'green', 'blue'], index = [0, 3, 5])
s1
# s1.reindex([0, 1, 2, 3, 4, 5, 6], method = 'ffill')           # forward filling

s1.reindex([0, 1, 2, 3, 4, 5, 6], method = 'bfill') # backwar filling 


0      red
1    green
2    green
3    green
4     blue
5     blue
6      NaN
dtype: object

In [48]:
msft = pd.read_csv('msft.csv', index_col=0)
aapl = pd.read_csv('aapl.csv', index_col=0)
msft.head(3)

Open   High    Low  Close    Volume  Adj Close
Date                                                       
2012-01-03  26.55  26.96  26.39  26.77  64731500   24.42183
2012-01-04  26.82  27.47  26.78  27.40  80516100   24.99657
2012-01-05  27.38  27.73  27.29  27.68  56081400   25.25201

In [49]:
aapl.head(2)

Open       High     Low      Close    Volume  Adj Close
Date                                                                    
2012-01-03  409.39996  412.50000  409.00  411.22998  75555200   55.41362
2012-01-04  410.00000  414.68002  409.28  413.44000  65005500   55.71143

In [50]:
msft.insert(0, 'Symbol', 'MSFT')
msft.head(2)

Symbol   Open   High    Low  Close    Volume  Adj Close
Date                                                              
2012-01-03   MSFT  26.55  26.96  26.39  26.77  64731500   24.42183
2012-01-04   MSFT  26.82  27.47  26.78  27.40  80516100   24.99657

In [51]:
aapl.insert(0, 'Symbol', 'AAPL')
aapl.head(2)

Symbol       Open       High     Low      Close    Volume  \
Date                                                                   
2012-01-03   AAPL  409.39996  412.50000  409.00  411.22998  75555200   
2012-01-04   AAPL  410.00000  414.68002  409.28  413.44000  65005500   

            Adj Close  
Date                   
2012-01-03   55.41362  
2012-01-04   55.71143

In [52]:
combined = pd.concat([msft, aapl]) # row wise concat
combined

Symbol       Open       High        Low      Close     Volume  \
Date                                                                       
2012-01-03   MSFT   26.55000   26.96000   26.39000   26.77000   64731500   
2012-01-04   MSFT   26.82000   27.47000   26.78000   27.40000   80516100   
2012-01-05   MSFT   27.38000   27.73000   27.29000   27.68000   56081400   
2012-01-06   MSFT   27.53000   28.19000   27.53000   28.11000   99455500   
2012-01-09   MSFT   28.05000   28.10000   27.72000   27.74000   59706800   
...           ...        ...        ...        ...        ...        ...   
2012-12-21   AAPL  512.46997  519.66998  510.24005  519.33002  149067100   
2012-12-24   AAPL  520.34998  524.25000  518.71002  520.16998   43938300   
2012-12-26   AAPL  519.00000  519.46002  511.12000  513.00000   75609100   
2012-12-27   AAPL  513.54004  516.25000  504.66003  515.06000  113780100   
2012-12-28   AAPL  510.28998  514.47998  508.12000  509.58997   88569600   

            Adj Close  
Date                   
2012-01-03   24.42183  
2012-01-04   24.99657  
2012-01-05   25.25201  
2012-01-06   25.64429  
2012-01-09   25.30675  
...               ...  
2012-12-21   70.60166  
2012-12-24   70.71585  
2012-12-26   69.74111  
2012-12-27   70.02116  
2012-12-28   69.27753  

[498 rows x 7 columns]

In [53]:
import datetime
pd.set_option('precision', 2)

In [54]:
# pd.DatetimeIndex(msft['Date'])
msft = msft.reset_index()
# msft['Date']
pd.DatetimeIndex(msft['Date'])

DatetimeIndex(['2012-01-03', '2012-01-04', '2012-01-05', '2012-01-06',
               '2012-01-09', '2012-01-10', '2012-01-11', '2012-01-12',
               '2012-01-13', '2012-01-17',
               ...
               '2012-12-14', '2012-12-17', '2012-12-18', '2012-12-19',
               '2012-12-20', '2012-12-21', '2012-12-24', '2012-12-26',
               '2012-12-27', '2012-12-28'],
              dtype='datetime64[ns]', name='Date', length=249, freq=None)

In [55]:
pd.DatetimeIndex(msft['Date']).year

Int64Index([2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012,
            ...
            2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012, 2012],
           dtype='int64', name='Date', length=249)

In [56]:
msft.head()
msft.iloc[1:3]
msft[1:3]

Date Symbol   Open   High    Low  Close    Volume  Adj Close
1  2012-01-04   MSFT  26.82  27.47  26.78  27.40  80516100      25.00
2  2012-01-05   MSFT  27.38  27.73  27.29  27.68  56081400      25.25

In [68]:
# for name, group in (msft.groupby('Date')):
#     print(name)
#     print(group)
# msft.groupby('Date').groups
msft.head()


Date Symbol   Open   High    Low  Close    Volume  Adj Close
0  2012-01-03   MSFT  26.55  26.96  26.39  26.77  64731500      24.42
1  2012-01-04   MSFT  26.82  27.47  26.78  27.40  80516100      25.00
2  2012-01-05   MSFT  27.38  27.73  27.29  27.68  56081400      25.25
3  2012-01-06   MSFT  27.53  28.19  27.53  28.11  99455500      25.64
4  2012-01-09   MSFT  28.05  28.10  27.72  27.74  59706800      25.31

In [71]:
msft.iloc[[1]]


Date Symbol   Open   High    Low  Close    Volume  Adj Close
1  2012-01-04   MSFT  26.82  27.47  26.78   27.4  80516100       25.0

In [72]:
msft[1:3]

Date Symbol   Open   High    Low  Close    Volume  Adj Close
1  2012-01-04   MSFT  26.82  27.47  26.78  27.40  80516100      25.00
2  2012-01-05   MSFT  27.38  27.73  27.29  27.68  56081400      25.25

In [23]:
class Person:
    def __init__(self, fname , lname):
        print('parent constructor called')
        self.fname = fname
        self.lastname = lname
        
    def printt(self):
        print('priting in parent ',  self.fname, self.lastname)

class Student(Person):
    def __init__(self,fname, lname,  idd):
        
        print('child constructor called')
        self.fname = fname
        self.lastname = lname
        self.id = idd
    def printt(self):
        print('child ',  self.fname, self.lastname, self.id)
        super().printt()

        
x = Student('Ahmad', 'Ali', 1221)
x.printt()

child constructor called
child  Ahmad Ali 1221
priting in parent  Ahmad Ali
